server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/dotnet/ {
    proxy_pass http://dotnet-api:5000;
  }

  location /api/ {
    proxy_pass http://spring-api:8080;
  }
}
